### ISSUE TITLE
Добавить кнопку "На предыдущий шаг"

### ISSUE THREAD

**Issue by IgorNikiforov** [ZabelinK/NII_LOR#33]
Не хватает возможности вернуться на предыдущий шаг в настройках, при обнаружении ошибки в настройке предыдущего шага.
Нужно добавить кнопку "На предыдущий шаг" на всех страничках.

**Comment by Ane1y** [comment]
Реализация в коммитах 53a1ca7ec4f5cf3bd822a125a69b08a3278435b5  и 57c27d6a6250c4467725d40c7452bb8ebc33ca89
