### ISSUE TITLE
Добавить новые атрибуты

### ISSUE THREAD

**Issue by AlexandraSokolova** [ZabelinK/NII_LOR#5]
1. Первое окно (Информация о пациенте)
+ Диагноз 
+ Дата операции (информация об оперативных вмешательствах)
2. Выбор записей
+ Свободное звуковое поле/наушники
+ Мужчина/женщина
+ Правое/левое ухо
+ Слуховой аппарат/Кохлеарный имплант
+ АД/АС/бинаурально (метод коррекции слуха) 
+ Модель слухового аппарата + программа (комментарий)

**Comment by maxvale** [comment]
Изменил логику настроек, о которой мы говорили, в коммите https://github.com/ZabelinK/NII_LOR/commit/052d389a2a25dea466860e83ab1b17b9aa62045e.
