### ISSUE TITLE
Переход на итеративный режим

### ISSUE THREAD

**Issue by maxvale** [ZabelinK/NII_LOR#8]
Необходимо переработать алгоритм работы приложения с пословного тестирования на тестирование итерациями:

1. Выбор сурдологом записей слов/предложений
2. Проигрывание данной дорожки с конфигурируемой задержкой между словами
3. Сохранение результатов данной итерации
4. Повторение тестирования с тем же пациентом при других настройках и записях

Реализовать прогресс бар для визуализации оставшихся слов в сессии

**Comment by IgorNikiforov** [comment]
@maxvale, напиши, пожалуйста, текущий статус по задаче:
 - что сделано
 - что осталось
Спасибо.

**Comment by maxvale** [comment]
Development continue in issue #31
