### ISSUE TITLE
Вынести настройки сессии в отдельное окно

### ISSUE THREAD

**Issue by maxvale** [ZabelinK/NII_LOR#9]
Вынести настройки с окна выбора записей, которые не имеют отношения к записям и шумам:

- Свободное звуковое поле/наушники
- Пол диктора записей
- Слуховой аппарат/имлант
- АС/АД/Бинаурально
- СА/КИ
- Модель аппарата

**Comment by kirillston** [comment]
Реализация представлена в коммите:
https://github.com/ZabelinK/NII_LOR/commit/3f01fb1791daf6906268ca9cb256b716edd50bdf

**Comment by maxvale** [comment]
Необходимо изменить левое и правое ухо на АС и АД в виде checkbox, а если выбраны оба - бинаурально. Все остальное просто супер!

**Comment by maxvale** [comment]
Изменил логику, о которой мы говорили, в коммите https://github.com/ZabelinK/NII_LOR/commit/052d389a2a25dea466860e83ab1b17b9aa62045e.
